# Chart repositories used from within this state file
#
# Use `helm-s3` and `helm-git` and whatever Helm Downloader plugins
# to use repositories other than the official repository or one backend by chartmuseum.
repositories:
  # To use official "stable" charts a.k.a https://github.com/helm/charts/tree/master/stable
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com

releases:
  - name: base
    chart: ./charts/base
    values:
      - ./values/main.yaml
  - name: api
    chart: ./charts/api
    namespace: core
  - name: postgres
    chart: stable/postgresql
    namespace: core
    values:
      # Hasura requires superuser to create extension.
      # This is "postgres" by default.
      # So do not provide another username
      # - postgresqlUsername: {{ requiredEnv "POSTGRES_USERNAME" }}
      - postgresqlPassword: {{ requiredEnv "POSTGRES_PASSWORD" }}
      - postgresqlDatabase: {{ requiredEnv "POSTGRES_DATABASE" }}
      - service:
          port: {{ requiredEnv "POSTGRES_ENDPOINT_PORT" }}
      - extraEnv: |
          - name: PGTZ
            value: {{ requiredEnv "POSTGRES_TIMEZONE" }}
  - name: hasura
    chart: ./charts/hasura
    namespace: core
    values:
      - adminSecret: {{ requiredEnv "HASURA_GRAPHQL_ADMIN_SECRET" }}
      - databaseUsername: {{ requiredEnv "POSTGRES_USERNAME" }}
      - databasePassword: {{ requiredEnv "POSTGRES_PASSWORD" }}
      - databaseEndpointIp: {{ requiredEnv "POSTGRES_ENDPOINT_IP" }}
      - databaseEndpointPort: {{ requiredEnv "POSTGRES_ENDPOINT_PORT" }}
      - databaseDatabase: {{ requiredEnv "POSTGRES_DATABASE" }}
      - logTypes: {{ requiredEnv "HASURA_GRAPHQL_ENABLED_LOG_TYPES"}}
