version: '3.7'

services:
  postgres:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_DB: ${HASURA_POSTGRES_DATABASE}
      POSTGRES_USER: ${HASURA_POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${HASURA_POSTGRES_PASSWORD}
      PGTZ: ${HASURA_POSTGRES_TIMEZONE}
    ports:
      - target: 5432
        published: ${HASURA_POSTGRES_ENDPOINT_PORT}
        protocol: tcp
        mode: host
    volumes:
      ## To executes ['initialization scripts'](https://hub.docker.com/_/postgres),
      ## uncomment the next line, create ./data directory, and add .sh or .sql files under ./data
      # - ./data:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
  graphql-engine:
    image: hasura/graphql-engine:v1.0.0.cli-migrations
    ports:
      - target: 8080
        published: ${HASURA_ENDPOINT_PORT}
        protocol: tcp
        mode: host
    volumes:
      - ./migrations:/hasura-migrations
    depends_on:
      - 'postgres'
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: '${HASURA_POSTGRES_PROTOCOL}://${HASURA_POSTGRES_USERNAME}:${HASURA_POSTGRES_PASSWORD}@postgres:5432/${HASURA_POSTGRES_DATABASE}'
      HASURA_GRAPHQL_ENABLE_CONSOLE: ${HASURA_GRAPHQL_ENABLE_CONSOLE}
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: ${HASURA_GRAPHQL_ENABLED_LOG_TYPES}
      HASURA_GRAPHQL_ADMIN_SECRET: '${HASURA_GRAPHQL_ADMIN_SECRET}'
volumes:
  postgres_data:
