apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.name }}
    hasuraService: custom
  name: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        env:
        - name: HASURA_GRAPHQL_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: {{ .Values.name }}
              key: databaseUrl
        - name: HASURA_GRAPHQL_ADMIN_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ .Values.name }}
              key: adminSecret
        - name: HASURA_GRAPHQL_ENABLE_CONSOLE
          valueFrom:
              configMapKeyRef:
                name: {{ .Values.name }}
                key: consoleEnabled
        - name: HASURA_GRAPHQL_ENABLED_LOG_TYPES
          valueFrom:
              configMapKeyRef:
                name: {{ .Values.name }}
                key: logTypes
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
