apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name | quote }}
type: Opaque
stringData:
  adminSecret: {{ required "Value 'adminSecret' is required." .Values.adminSecret | quote}}
  databaseUrl: "{{ .Values.database.protocol }}://{{ .Values.database.username }}:{{ .Values.database.password }}@{{ .Values.database.endpoint.ip }}:{{ .Values.database.endpoint.port }}/{{ .Values.database.database }}"
