apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name | quote }}
type: Opaque
stringData:
  adminSecret: {{ required "Value 'adminSecret' is required." .Values.adminSecret | quote}}
  databaseUrl: "postgres://{{ .Values.databaseUsername }}:{{ .Values.databasePassword }}@{{ .Values.databaseEndpointIp }}:{{ .Values.databaseEndpointPort }}/{{ .Values.databaseDatabase }}"
