apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.name }}
  name: {{ .Values.name }}
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: {{ .Values.name }}
  type: {{ .Values.service.type }}
