name: hello

on:
  pull_request:
    paths:
      - 'packages/hello/**'

jobs:
  test:
    strategy:
      matrix:
        package: [hello]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Read .nvmrc
        id: nvmrc
        run: echo "::set-output name=nvmrc::$(cat .nvmrc)"
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ steps.nvmrc.outputs.nvmrc }}
      - name: Get yarn cache
        id: yarn-cache-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: yarn install
        run: yarn install --silent --frozen-lockfile
      - name: lint
        run: yarn lint packages/${{ matrix.package }}
      - name: lint:md
        run: yarn lint:md packages/${{ matrix.package }}
      - name: test and coverage
        working-directory: ./packages/${{ matrix.package }}
        run: yarn coverage
